version: 1

formatters:
  verbose:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: verbose
    stream: ext://sys.stdout
  tofile:
    class: logging.FileHandler
    level: DEBUG
    formatter: verbose
    filename: app.log

# Default handler if not logger provided
root:
    level: INFO
    handlers: [console]
