version: 1

formatters:
  verbose:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: verbose
    stream: ext://sys.stdout
  tofile:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: verbose
    filename: app.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf8

# Default handler if not logger provided
root:
    level: INFO
    handlers: [console, tofile]
